# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Distributed Nonsense
email: joseph.rawlings@gmail.com
description: >
  Random thoughts from a distributed software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joerawlings.com" # the base hostname & protocol for your site
twitter_username: joerawlings
github_username:  jrawlings
linkedin_username: rawlingsjoe
github: site.github.joerawlings.com

# Build settings
markdown: kramdown
